SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE application CASCADE;
DROP TABLE milestone CASCADE;
DROP TABLE payment CASCADE;
DROP TABLE project CASCADE;
DROP TABLE review CASCADE;
DROP TABLE skill CASCADE;
DROP TABLE skill_project CASCADE;
DROP TABLE skill_user CASCADE;
DROP TABLE team CASCADE;
DROP TABLE team_user CASCADE;
DROP TABLE user CASCADE;